### ISSUE TITLE
How to support other executors?

### ISSUE THREAD

**Issue by cursorkey** [mleoking/PromptAppGPT#1]
Great!
But, how to support other executors like vicuna, stable difussion, etc., even other non-AI executors like xmind and excel?

**Comment by mleoking** [comment]
Recently some new & important executors are added: bingWeb (Search), bingImage(Search), webFetch, javaScript (for js code running).

To develop new executors:

1. Define new executors in the pagExe object in:

https://github.com/mleoking/PromptAppGPT/blob/main/js/prompt-app-gpt-app-executor.js

2. Register new executors in the appRunPrompt function in:

https://github.com/mleoking/PromptAppGPT/blob/main/js/prompt-app-gpt-app.js

You can refer to the code of bingWeb executors to define all web access related executors. For non web executors, you can use a js container (e.g. Electron, niva) that allows you to access the command and get results.

**Comment by cursorkey** [comment]
Thank you so much. I'll take a try.
